### PR TITLE
Ui sprint1 oct2015

### PR DESCRIPTION
**Pull request by n8fr8**
still working on this...

### CODE REVIEW

**Comment by eighthave** [comment]
- `/sticker` seems like something that people might hit every now and then.  Is there a way to do this by sticking some data into an XMPP packet rather than in the message itself?  The `/sticker` will also show up in the message on non-Zom XMPP clients.
- In 2fbf0d6a6b0d8e56ec60c26e1c896f9b66da8a49, the fav/send/share is `GONE` only for PNG files. All other image files have fav/send/share set to `VISIBLE`.  Is that deliberate?  Why hide for only particular format of image?

**Comment by n8fr8** [comment]
I will look into another way to do the /sticker command. I may have it just fail to being a normal message if it doesn't actual match a sticker code we have.

My intention was to not show then for stickers, which are all PNG. I was also thinking of only having the fav/send/share show up when you open the full image. It tends to get in the way for smaller images like stickers.

**Comment by eighthave** [comment]
I don't think sharing PNG files is super common, but I doubt it is rare.  Treating PNGs differently will be odd for users who do share them.  Can the fav/send/share be hidden based on the sticker command?

**Comment by eighthave** [comment]
Also, I guess the sticker code should really be stuck in the OTR packet so it is private.  What about using a URI format?  `sticker:smiling-cat.png` that would make it easily parsable and somewhat human readable.  Something like the emoji codes that Skype and other apps send, something like `:poo:`

**Comment by eighthave** [comment]
last though on this: if the sticker tag will show as text when it does not match a sticker, then I think people will basically never have problems with it, i.e. if `sticker:smiling-cat.png` gets sent, and there is no "smiling-cat.png" sticker, then just show the text as it is.

**Comment by n8fr8** [comment]
Since this is for MUC chat, and we don't have mpOTR/n+1 yet, then we can't use an OTR packet. I will make sure it fails in the proper way if there is no relevant sticker text. I did like the idea of supporting some irc like "/foo" commands as a general approach, since Slack has done the same thing.

**Comment by eighthave** [comment]
As far as I can tell, this code still has the issue that I mentioned before: if the `/sticker` cmd does not match an actual sticker, it should print that cmd as plain text.  Right now, this code seems to eat all messages that start with `/` and only print anything if it starts with `/sticker` and that matches an included sticker.

**Comment by eighthave** [comment]
that will surely cause problems, for example, if someone pastes a file path into the chat, the whole message will disappear

**Comment by n8fr8** [comment]
What is meant to be happening is that if the sticker does not exist as an image asset, then it display the original string. I have tested that, and it appears to be working. All of this logic is in the MessageListItem inbound rendering chunk.

**Comment by eighthave** [comment]
ok, that's good, I was looking at `ConversationListItem` where you added the /sticker command.

**Pull request merged**
