### PR TITLE
Create group activity

### PR DESCRIPTION
**Pull request by N-Pex**
Implement the "tag view" when selecting multiple contacts for a group.

Also, minor fixes in group detail view (mute and title/back button).

### CODE REVIEW

**Comment by n8fr8** [comment]
I think you are missing these strings turn_notifications_on turn_notifications_off

**Comment by n8fr8** [comment]
Otherwise, looking good! Integrated and testing here.

**Comment by N-Pex** [comment]
Great, thanks! Strange, the strings are definitely checked in (https://github.com/N-Pex/Zom-Android/blob/7c96eb56fe39a6522cc07a6318577fcf244b73c0/app/src/main/res/values/zomstrings.xml)

Maybe a merge bug?

**Comment by n8fr8** [comment]
Sorry, it was just a slow resource building process.... all is well!

**Pull request merged**
