### PR TITLE
Auto-answer subscription request if we already have a one-way subscri…

### PR DESCRIPTION
**Pull request by N-Pex**
…ption.

Fixes https://github.com/zom/Zom-iOS/issues/506

I don't have the whole picture here, so please have a look @n8fr8. Android does (no longer?) auto answer the subscription request when the other end has approved us and tries to add us back.

### CODE REVIEW

**Comment by n8fr8** [comment]
Ah, thanks, will take a look. One thing I fixed is that previous I was using Async Stanza listeners in Smack, which apparently doesn't guarantee correct order. This could account for some of the issue we faced with confusing order of subscription handling.

Otherwise, yes, checking at roster load makes sense!

**Comment by n8fr8** [comment]
Hmm, OTOH, just because someone has allowed me to see their presence, doesn't mean I want to automatically let them see mine. That is why we have auto approve subscriptions off.

**Comment by N-Pex** [comment]
Yes, but if they are on your roster you have already added them there, so should be safe.

**Comment by N-Pex** [comment]
Or else we need to rework the whole flow here, we can't just enter a chat when one part hits "Approve".

**Comment by n8fr8** [comment]
I am confused about rosters... lets talk on the dev scrum!

**Comment by N-Pex** [comment]
Yup, let's talk, I am probably as confused =)

**Comment by n8fr8** [comment]
It is technically possible to have someone in your roster, without having a subscription to or from them, as explained in "2.1.2.5.  Subscription Attribute"
https://xmpp.org/rfcs/rfc6121.html#roster-syntax-items-subscription

However, it is also true that you should be able to send a message to someone regardless of subscription status, so the "Accept" and open chat model should work.

**Comment by tiffrobo** [comment]
@n8fr8 Have you been able to address this in the next Android build? We are still seeing this issue between iOS (build 119) and Android.

**Comment by n8fr8** [comment]
Yes, I reworked the whole, and I think my new code will handle all tihs appropriately now. Closing this pull request, but please test with the build from Friday.

**Pull request closed without merging**
