### PR TITLE
ChatSecure-Push Draft Implementation

### PR DESCRIPTION
**Pull request by OnlyInAmerica**
This adds preliminary ChatSecure-Push support Zom. However, Zom's current always-online design means there are virtually no user-visible changes for a Zom-Android user.

**Overview**

[ChatSecure-Push is initialized](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/ImApp.java#L978) during app start: This involves fetching GCM credentials, authenticating a ChatSecure-Push account  with a random username/password (stored in a SqlCipher table managed by `ImpsProvider`), and registering a pushable device.

The first message a user sends via `ChatSession` in an OTR session will be [accompanied by a ChatSecure-Push Whitelist token exchange](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/model/ChatSession.java#L125) over OTR TLV. Receiving these Whitelist token TLVs is handled by a new [`WhitelistTokenTlvHandler`](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/push/WhitelistTokenTlvHandler.java) which implements `OtrTlvHandler` and is managed by `OtrChatManager` similiar to `OtrSm`.

If the user sends a message via `ChatSessoin` to an offline contact, [a ChatSecure-Push push message will be sent](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/model/ChatSession.java#L123) to the offline contact informing them that "'Username' wants to Chat". Clicking the notification will bring the user to `ConversationDetailActivity` where traditional OTR chatting can commence.

**Implementation Notes**

Zom-Android only goes offline as a result of a "Force Quit" operation, but this action will also stop the app from receiving GCM messages until the next time the app is opened (and thus the user will be connected) or phone boot. This means that a Zom-Android user is unlikely to ever receive a ChatSecure-Push message by virture of the app either being online or completely stopped but this will improve the experience between Android and iOS clients. Furthermore, it will be feasible come XMPP server support for XEP-0357 for AwesomeAppCore to migrate away from the always-connected model.

**Zom-Android Issues**
I've made a few observations that I can open as separate Issues, but since their behavior affects the general demo-ability of push messaging I thought I'd include them here as well.

Zom-Android seems to occasionally send messages plaintext before an OTR session is established (This is probably unwanted behavior!). ChatSecure-Push will not be available between two Zom-Android contacts until they've exchanged chat messages across an OTR session.

I've seen Zom-Android get into states where the "Send Message" button performs no action because [ConversationView#createChatSession()](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/ui/ConversationView.java#L1685) returns null.

### CODE REVIEW

**Comment by n8fr8** [comment]
A lot to review here. Thanks for the detailed write-up. As an aside, we did an an online toggle switch into the "me" tab, so users can choose to do this manually. We should consider how that interacts with GCM.
Obviously this work is also critical for handling the new Doze feature in Android M, which GCM can only wake a device from.

**Comment by n8fr8** [comment]
Btw, do we need to do any special signing or other process during the build/release?

**Comment by OnlyInAmerica** [comment]
Oh-right! I should have mentioned: This build will require setting up two external dependencies: A GCM project and your ChatSecure-Push Server. Steps are outlined [here](https://github.com/ChatSecure/ChatSecure-Push-Android#requirements).

**GCM**
Register a [Google Cloud Messaging project](https://developers.google.com/mobile/add) and obtain a `google-services.json` file that you bundle in the root directory of your application module. e.g: `./awesomeAppCore/google-services.json`.

This reminds me that this PR will not pass the Travis check unless I bundle a stub `google-services.json` file...

**ChatSecure-Push Server**
This PR configures Zom-Android's new [`PushManager`](https://github.com/OnlyInAmerica/Zom-Android/blob/csp/awesomeAppCore/src/main/java/org/awesomeapp/messenger/push/PushManager.java#L72) class to operate by default with the ChatSecure-Push demo Heroku instance at https://chatsecure-push.herokuapp.com/api/v1

If you'd like a quick-and-easy way to demo this week, I have test builds configured with my own GCM project and the ChatSecure-Push demo Heroku instance. Here's an [.apk](https://s3.amazonaws.com/dbro/zom-push-alpha1.apk) that sends a push on every outgoing message (For easier demoing / testing of the push function).

**Comment by OnlyInAmerica** [comment]
Just a heads-up that there seems to be issues establishing OTR sessions between current Zom-Android and ChatSecure-iOS. I've opened [this issue](https://dev.guardianproject.info/issues/5942) to track that discussion.

**Comment by eighthave** [comment]
So will PushSecure always require that the clients use GCM?  Using GCM is a bummer since it is not free, open source software.

**Comment by n8fr8** [comment]
On the Zom front, GCM won't be required, and it is a ping-pull implementation after all.

**Comment by OnlyInAmerica** [comment]
The ChatSecure-Push specification is agnostic to the push mechanism used, but our [reference implementation of the Push Server](https://github.com/ChatSecure/ChatSecure-Push-Server) currently only supports GCM and APNS.

@n8fr8 To make sure I understand: You're saying GCM won't be required for Zom by virtue of the app being always-online? ~~On that front it's worth noting that always-online behavior will be a bit more difficult with Android M's App Standby, so it might be worth investigating a design without that assumption.~~ Turns out your foreground service + notification should [exempt you from App Standby](https://developer.android.com/intl/ko/training/monitoring-device-state/doze-standby.html#understand_app_standby), but Zom may lose network access during Doze.

**Comment by n8fr8** [comment]
We definitely want to support all the things, and let the user do all the things! One big issue is that GCM may not work at all in China, and so we'll have to eventually figure out how to use Xiaomi or Baidu's push services there (which I think Amazon supports with their generic push infrastructure). Otherwise, we are all on the same page here!

**Comment by eighthave** [comment]
This pull request requires the GCM binary blob, that's what I'm referring to.  I've heard that people are working on a free software replacement for that, so that 100% free software apps can still use GCM.

**Comment by n8fr8** [comment]
So... finally getting around to merging, building, testing this... and it seems jdk8 is a requirement now, due to the lambda / retrolambda dependency?

https://github.com/evant/gradle-retrolambda

**Comment by n8fr8** [comment]
The issue is that we have to now setup jdk8 on our build, release machines, etc. 

I get that lambda expressions are cool and concise, but I wasn't expecting this just to support push.

**Comment by OnlyInAmerica** [comment]
Oh pardon! We moved use of that dependency out into the sample app, but the entry in the `sdk`'s `build.gradle` file lingered. That can be safely removed. Will take a stab first thing tomorrow morning.

**Comment by n8fr8** [comment]
Great thanks!

**Comment by n8fr8** [comment]
I've manually reintegrated this work over here based on your excellent effort and examples: https://github.com/zom/Zom-Android/pull/71

**Pull request closed without merging**
