### PR TITLE
WIP: Group detail view

### PR DESCRIPTION
**Pull request by N-Pex**

### CODE REVIEW

**Comment by n8fr8** [comment]
Compiles, runs and looks good!

**Comment by n8fr8** [comment]
Should we remove "SHARE" now, since we only want to add existing contacts? Same perhaps for the QR code. Let's discuss more on Wednesday?

Otherwise, should I reconnect the "add contacts" button, or are you working on that?

**Comment by N-Pex** [comment]
Yes, I guess we should remove them for now.

I am currently on the iOS side, so please do, unless you want me to do that later!

**Comment by n8fr8** [comment]
No worries I got it. Going to do a build today.

**Pull request merged**
